//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Aritist
    {

        public int Aritist_Id { get; set; }
        [DisplayName("Aritist Name")]
        public string Aritist_name { get; set; }
        [DisplayName("Aritist Band")]
        public string Aritist_Band { get; set; }
        [DisplayName("Image")]
        public string Aritist_Image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }


        public Aritist()
        {
            Aritist_Image = "~/APPFile/Images/default.jpg";
        }
    }
}
